(source gnu)
(source melpa)
(source marmalade)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")

(depends-on "pallet")
(depends-on "init-loader")

(depends-on "ag")
(depends-on "go-mode")
(depends-on "android-mode")
(depends-on "php-mode")
(depends-on "epc")
(depends-on "mmm-mode")

(depends-on "wgrep-ag")
(depends-on "go-eldoc")
(depends-on "jedi")
(depends-on "helm-gtags")

(depends-on "ansible")
(depends-on "yaml-mode")

(depends-on "markdown-mode")
